### ISSUE TITLE
How to use the plugin with karma ?

### ISSUE THREAD

**Issue by dhoko** [dtinth/babel-plugin-__coverage__#34]
Hi,

I tried to replace *isparta*... but it doesn't work :/

```
07 06 2016 14:02:48.030:ERROR [coverage]: [TypeError: Cannot read property 'start' of undefined]                                
TypeError: Cannot read property 'start' of undefined                                                                            
    at /home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_modules/karma-coverage/node_modules/
istanbul/lib/object-utils.js:59:44                                                                                              
    at Array.forEach (native)                                                                                                   
    at Object.addDerivedInfoForFile (/home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_module
s/karma-coverage/node_modules/istanbul/lib/object-utils.js:58:37)                                                               
    at Object.Collector.fileCoverageFor (/home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_mo
dules/karma-coverage/node_modules/istanbul/lib/collector.js:94:15)                                                              
    at /home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_modules/karma-coverage/node_modules/
istanbul/lib/report/lcovonly.js:96:65                                                                                           
    at Array.forEach (native)                                                                                                   
    at /home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_modules/karma-coverage/node_modules/
istanbul/lib/report/lcovonly.js:95:31                                                                                           
    at SyncFileWriter.extend.writeFile (/home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_mod
ules/karma-coverage/node_modules/istanbul/lib/util/file-writer.js:57:9)                                                         
    at FileWriter.extend.writeFile (/home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_modules
/karma-coverage/node_modules/istanbul/lib/util/file-writer.js:147:23)                                                           
    at LcovOnlyReport.Report.mix.writeReport (/home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/no
de_modules/karma-coverage/node_modules/istanbul/lib/report/lcovonly.js:94:16)                                                   
    at LcovReport.Report.mix.writeReport (/home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_m
odules/karma-coverage/node_modules/istanbul/lib/report/lcov.js:54:19)                                                           
    at writeReport (/home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_modules/karma-coverage/
lib/reporter.js:62:16)                                                                                                          
    at /home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_modules/karma-coverage/lib/reporter.
js:290:11                                                                                                                       
    at /home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/node_modules/karma/lib/helper.js:82:7    
    at FSReqWrap.oncomplete (fs.js:82:15) 
```

karma.config.js

```js

// You can remove these lines, still does not work
babelPreprocessor: {
  options: {
    presets: ['es2015'],
    plugins: [ '__coverage__' ]
  }
},

 // With or without, all or only the two ['babel'']
preprocessors: {
  // '../../src/{Core,App}/**/!(isInviewPort|index|repeater).js': ['coverage'],
  '../../src/{Core,App}/**/*.js': ['babel'],
  'src/**/*.js': ['babel'],
},

coverageReporter: {
  // instrumenters: {
  //   isparta : require('isparta')
  // },
  // instrumenter: {
  //   '../../src/{Core,App}/**/**/*.js': 'isparta',
  //   'src/**/*.js': 'isparta'
  // },
  // instrumenterOptions: {
  //   isparta: {
  //     babel: {
  //       presets: 'es2015'
  //     }
  //   }
  // },
  reporters:[
    {type: 'html', dir: '../coverage/'},
    {type: 'clover', dir: '../coverage/clover/'}
  ]
},
reporters: ['progress', 'coverage', 'junit'],
junitReporter: {
  outputDir: '../coverage',
  outputFile: 'test-results.xml'
},
```

I don't use webpack so, tried to adapt [your configuration](https://github.com/bemusic/bemuse/blob/master/karma.conf.js) but was not able to make it work. Do you have something without webpack ?

**Comment by dtinth** [comment]
I have tried a simple karma+babel+\_\_coverage\_\_ example, and it works fine. However this problem usually happens when the plugin produces an invalid line number mapping. This is a rare bug.

Can you try adding some `console.log` to `object-utils.js` and see which file the plugin made the mistake, and if possible, can I have a look at that file? Also, can I have the preprocessed version of that file? (You can find it by going to `localhost:9876/debug.html`. Its source code will contain script tags that links to the preprocessed file.)

**Comment by dhoko** [comment]
Ex:

### Src:

```js
angular.module('analytics', ['ui.router'])
  .run(($rootScope, trackerApi, eventTracker) => {

    trackerApi.start();

    $rootScope.$on('$stateChangeSuccess', (e, state, params) => {
      eventTracker()
        .onIdle(angular.extend({
          stateName: state.name.replace(/\./g, '-')
        }, params), true);
    });
  });
```

### console.log `object-utils.js` L57
```js
{ path: '/home/dhoko/dev/front-app/src/SquareCo/AngularBundle/Resources/public/src/Core/analytics/index.js',
  s: 
   { '1': 364,
     '2': 177,
     '3': 1223,
     '4': 41,
     '5': null,
     '6': null,
     '7': null,
     '8': null,
     '9': null,
     '10': null,
     '11': null,
     '12': null,
     '13': null,
     '14': null,
     '15': null,
     '16': null,
     '17': null,
     '18': null,
     '19': null,
     '20': null,
     '21': null,
     '22': null,
     '23': null,
     '24': null,
     '25': null,
     '26': null,
     '27': null,
     '28': null,
     '29': null,
     '30': null,
     '31': null,
     '32': null,
     '33': null,
     '34': null,
     '35': null,
     '36': null,
     '37': null,
     '38': null,
     '39': null,
     '40': null,
     '41': null,
     '42': null,
     '43': null,
     '44': null,
     '45': null,
     '46': null,
     '47': null,
     '48': null,
     '49': null,
     '50': null,
     '51': null,
     '52': null,
     '53': null,
     '54': null,
     '55': null,
     '56': null,
     '57': null,
     '58': null,
     '59': null,
     '60': null,
     '61': null,
     '62': null,
     '63': null,
     '64': null,
     '65': null,
     '66': null,
     '67': null,
     '68': null,
     '69': null,
     '70': null,
     '71': null,
     '72': null,
     '73': null,
     '74': null,
     '75': null,
     '76': null,
     '77': null,
     '78': null,
     '79': null,
     '80': null,
     '81': null,
     '82': null,
     '83': null,
     '84': null,
     '85': null,
     '86': null,
     '87': null,
     '88': null,
     '89': null,
     '90': null,
     '91': null,
     '92': null,
     '93': null,
     '94': null,
     '95': null,
     '96': null,
     '97': null,
     '98': null,
     '99': null,
     '100': null,
     '101': null,
     '102': null,
     '103': null,
     '104': null,
     '105': null,
     '106': null,
     '107': null,
     '108': null,
     '109': null,
     '110': null,
     '111': null,
     '112': null,
     '113': null,
     '114': null,
     '115': null,
     '116': null,
     '117': null,
     '118': null,
     '119': null,
     '120': null,
     '121': null,
     '122': null,
     '123': null,
     '124': null,
     '125': null,
     '126': null,
     '127': null,
     '128': null,
     '129': null,
     '130': null,
     '131': null,
     '132': null,
     '133': null,
     '134': null,
     '135': null,
     '136': null,
     '137': null,
     '138': null,
     '139': null,
     '140': null,
     '141': null,
     '142': null,
     '143': null,
     '144': null,
     '145': null,
     '146': null,
     '147': null,
     '148': null,
     '149': null,
     '150': null,
     '151': null,
     '152': null,
     '153': null,
     '154': null,
     '155': null,
     '156': null,
     '157': null,
     '158': null,
     '159': null,
     '160': null,
     '161': null,
     '162': null,
     '163': null,
     '164': null,
     '165': null,
     '166': null,
     '167': null,
     '168': null,
     '169': null,
     '170': null,
     '171': null,
     '172': null,
     '173': null,
     '174': null,
     '175': null,
     '176': null,
     '177': null,
     '178': null,
     '179': null,
     '180': null,
     '181': null,
     '182': null,
     '183': null,
     '184': null,
     '185': null,
     '186': null,
     '187': null,
     '188': null,
     '189': null,
     '190': null,
     '191': null,
     '192': null,
     '193': null,
     '194': null,
     '195': null,
     '196': null,
     '197': null,
     '198': null,
     '199': null,
     '200': null,
     '201': null,
     '202': null,
     '203': null,
     '204': null,
     '205': null,
     '206': null,
     '207': null,
     '208': null,
     '209': null,
     '210': null,
     '211': null,
     '212': null,
     '213': null,
     '214': null,
     '215': null,
     '216': null,
     '217': null,
     '218': null,
     '219': null,
     '220': null,
     '221': null,
     '222': null,
     '223': null,
     '224': null,
     '225': null,
     '226': null,
     '227': null,
     '228': null,
     '229': null,
     '230': null,
     '231': null,
     '232': null,
     '233': null,
     '234': null,
     '235': null,
     '236': null,
     '237': null,
     '238': null,
     '239': null,
     '241': null,
     '242': null,
     '243': null,
     '244': null,
     '245': null,
     '246': null,
     '247': null,
     '248': null,
     '249': null,
     '250': null,
     '251': null,
     '252': null,
     '253': null,
     '254': null,
     '255': null,
     '256': null,
     '257': null,
     '258': null,
     '259': null,
     '260': null,
     '261': null,
     '262': null,
     '263': null,
     '265': null,
     '266': null,
     '267': null,
     '268': null,
     '269': null,
     '270': null,
     '271': null,
     '272': null,
     '273': null,
     '274': null,
     '275': null,
     '276': null,
     '277': null,
     '278': null,
     '280': null,
     '282': null,
     '283': null,
     '284': null,
     '286': null,
     '287': null,
     '288': null,
     '289': null,
     '290': null,
     '291': null,
     '292': null,
     '293': null,
     '294': null,
     '295': null,
     '296': null,
     '297': null,
     '298': null,
     '299': null,
     '300': null,
     '301': null,
     '302': null,
     '303': null,
     '304': null,
     '305': null,
     '306': null,
     '307': null,
     '308': null,
     '310': null,
     '312': null,
     '313': null,
     '314': null,
     '316': null,
     '317': null,
     '318': null,
     '319': null,
     '321': null,
     '322': null,
     '323': null,
     '325': null,
     '327': null,
     '328': null,
     '329': null,
     '330': null,
     '332': null,
     '334': null,
     '335': null,
     '336': null,
     '338': null,
     '340': null,
     '342': null,
     '344': null,
     '345': null,
     '346': null,
     '347': null,
     '348': null,
     '350': null,
     '352': null,
     '354': null,
     '357': null,
     '362': null,
     '363': null,
     '365': null,
     '368': null,
     '371': null,
     '372': null,
     '374': null,
     '377': null },
  b: {},
  f: 
   { '1': 178,
     '2': 1102,
     '3': null,
     '4': null,
     '5': null,
     '6': null,
     '7': null,
     '8': null,
     '9': null,
     '10': null,
     '11': null,
     '12': null,
     '13': null,
     '14': null,
     '15': null,
     '16': null,
     '17': null,
     '18': null,
     '19': null,
     '20': null,
     '21': null,
     '22': null,
     '23': null,
     '24': null,
     '25': null,
     '26': null,
     '27': null,
     '28': null,
     '29': null,
     '30': null,
     '31': null,
     '32': null,
     '33': null,
     '34': null,
     '35': null,
     '36': null,
     '37': null,
     '38': null,
     '39': null,
     '40': null,
     '41': null,
     '42': null,
     '43': null,
     '44': null,
     '45': null,
     '46': null,
     '47': null,
     '48': null,
     '49': null,
     '50': null,
     '51': null,
     '52': null,
     '53': null,
     '54': null,
     '55': null,
     '56': null,
     '57': null,
     '58': null,
     '59': null,
     '60': null,
     '61': null,
     '62': null,
     '63': null,
     '64': null,
     '65': null,
     '66': null,
     '67': null,
     '68': null,
     '69': null,
     '70': null,
     '71': null,
     '72': null,
     '73': null,
     '74': null,
     '75': null,
     '76': null,
     '77': null,
     '78': null,
     '79': null,
     '80': null,
     '81': null,
     '82': null,
     '83': null,
     '85': null,
     '86': null,
     '87': null,
     '89': null,
     '90': null,
     '91': null,
     '92': null,
     '93': null,
     '95': null,
     '96': null,
     '97': null,
     '98': null,
     '99': null,
     '100': null,
     '101': null,
     '102': null,
     '103': null,
     '104': null,
     '106': null,
     '108': null,
     '110': null,
     '113': null,
     '114': null,
     '116': null,
     '117': null,
     '120': null,
     '121': null,
     '124': null,
     '126': null,
     '128': null,
     '131': null,
     '132': null,
     '135': null,
     '138': null,
     '139': null,
     '141': null,
     '142': null,
     '144': null,
     '149': null,
     '150': null,
     '153': null,
     '157': null,
     '163': null,
     '167': null },
  statementMap: 
   { '1': { start: [Object], end: [Object] },
     '2': { start: [Object], end: [Object] },
     '3': { start: [Object], end: [Object] },
     '4': { start: [Object], end: [Object] } },
  fnMap: 
   { '1': { name: null, line: 2, loc: [Object] },
     '2': { name: null, line: 6, loc: [Object] } },
  branchMap: {},
  hash: '19056bcecb06455b29158e2f6a955d53' }
```

Only 4 statements (*statementMap*) but a list of 377 (*json.s*).
